stages:
  - build
  - test
  - post
  - deploy

variables:
  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"

# Root job that other jobs extend
.root:
  image: "juliagpu/julia:${CI_VERSION_TAG}-${CI_IMAGE_TAG}"
  only:
    variables:
      - $CI_IMAGE_TAG
      - $CI_VERSION_TAG

.test:
  extends: .root
  stage: test
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
    - julia --project -e 'using Pkg;
                          Pkg.instantiate();
                          Pkg.build();
                          Pkg.test(; coverage=true);'
  artifacts:
    when: always
    paths:
      - Manifest.toml
      - .julia/
      - deps/ext.jl
      - deps/build.log
      # gitlab-runner#2620
      - src/*.cov
      - src/*/*.cov
      - src/*/*/*.cov

.coverage:
  stage: post
  script:
    - julia --project -e 'using Pkg;
                          Pkg.add("Coverage")'
    - julia --project -e 'using Coverage;
                          cl, tl = get_summary(process_folder());
                          println("(", cl/tl*100, "%) covered");
                          Codecov.submit_local(process_folder(), ".")'
  coverage: '/\(\d+.\d+\%\) covered/'

.documentation:
  stage: post
  extends: .root
  variables:
    DOCUMENTER_DEBUG: "true"
  script:
    - julia --project=docs/ -e 'using Pkg;
                                Pkg.develop(PackageSpec(path=pwd()));
                                Pkg.instantiate()'
    - julia --project=docs/ docs/make.jl
  artifacts:
    paths:
    - docs/build
